server:
  port: 8089
spring:
  application:
    name: codecopy
  profiles:
    active: dev
  datasource:
    # 注意mysql 时区 字符集编码
    url: jdbc:mysql://127.0.0.1:3306/sqltest?autoReconnect=true&serverTimezone=UTC
    username: root
    password: 111
    type: com.alibaba.druid.pool.DruidDataSource
    # redis 配置
  redis:
    host: localhost
    port: 6379
    jedis.pool.max-wait: -1ms
    timeout: 2000ms
  jpa: #jpa配置
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      ddl-auto: none
    show-sql: true

shorturl:
  pre: http://localhost:8089/u/

token:
  # aes 密钥
  aeskey: f24fea293ac8bd5a6439f3ca3df746ae
  # rsa 公钥
  publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALbcdLKOtTKOjalffv/LLLOqfyh8Ep4XHjvOivMU3Nb1N0puG4+NTrXBS8GDczgsZ+7J6D7FTcH8JInMKpz85LMCAwEAAQ==
  # rsa 密钥
  secretkey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAttx0so61Mo6NqV9+/8sss6p/KHwSnhceO86K8xTc1vU3Sm4bj41OtcFLwYNzOCxn7snoPsVNwfwkicwqnPzkswIDAQABAkBGw9Xda+Cvaf9kdnJdZzErbmW7Mxi5WVT37BxVqdM01BTjudKSADlLn53fEeWl7pmfMkMuXZ7uPNdqmLWVLMNxAiEA6LXvDTKtEZNyTvjXs4nDJweiIT9kZtZmYD3hVcQueJUCIQDJKV+PcdKehVw8U+hdeE4/NZDFCHRzaGM4Zs5YRRbuJwIgSG0fSn9EKB04zWVbVNCCgWo5xplBOVRvJnL758KYKAUCIDdpmzZDb3ZVXCwOHRMqYbuNwNxV0OY9mh9eSncMSR2/AiEApSModT03Kr+nHxhgzAyOvzLcKE0IPMJ+ny3mjdyBjWc=
  url:
    validToken:  http://localhost:8089/api/v1/validToken


redis:
  subsection:
    subkey: onenum
    initValue: 101
    step: 20