server:
  port: 9052
spring:
  application:
    name: codecopy
  datasource:
    # 注意mysql 时区 字符集编码
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&serverTimezone=UTC
    username: root
    password: 111
    type: com.alibaba.druid.pool.DruidDataSource

